#!/usr/bin/env ruby
oldrev, newrev = ARGV

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

run "shards update --production --ignore-crystal-version"

run "shards build openloft.cr --release --ignore-crystal-version"

run "npm install"

run "npm run release"