#!/usr/bin/env ruby
oldrev, newrev = ARGV

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

run "shards install --production"

run "shards build openloft.cr --release"

run "npm install"

run "npm run release"